### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ghost** [Gael-de-Sailly/valleys_mapgen#1]
I know this is a work in progress, I'm only reporting this crash as a mere information, hoping that will help to polish a bit more this great mod. Sorry I couldn't help more but mapgen is far away of my programming skills :-)

This was on default minetest_game (with valleys_mapgen of course) at -95.0, 22.5, 253.0, seed: 17544283114256957415

2015-05-26 21:30:53: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
2015-05-26 21:30:53: ERROR[main]: ....minetest/games/mapgen/mods/valleys_mapgen/trees.lua:170: bad argument #2 to 'random' (interval is empty)
2015-05-26 21:30:53: ERROR[main]: stack traceback:
2015-05-26 21:30:53: ERROR[main]:   [C]: in function 'random'
2015-05-26 21:30:53: ERROR[main]:   ....minetest/games/mapgen/mods/valleys_mapgen/trees.lua:170: in function 'make_leavesblob'
2015-05-26 21:30:53: ERROR[main]:   ....minetest/games/mapgen/mods/valleys_mapgen/trees.lua:128: in function 'grow_jungle_tree'
2015-05-26 21:30:53: ERROR[main]:   ...minetest/games/mapgen/mods/valleys_mapgen/mapgen.lua:322: in function '?'
2015-05-26 21:30:53: ERROR[main]:   ...e/ivan/minetest-dev/bin/../builtin/game/register.lua:341: in function <...e/ivan/minetest-dev/bin/../builtin/game/register.lua:329>

In thread 7f57e897e780:
/home/ivan/minetest-dev/src/server.cpp:494: void Server::step(float): A fatal error occurred: ....minetest/games/mapgen/mods/valleys_mapgen/trees.lua:170: bad argument #2 to 'random' (interval is empty)
stack traceback:
    [C]: in function 'random'
    ....minetest/games/mapgen/mods/valleys_mapgen/trees.lua:170: in function 'make_leavesblob'
    ....minetest/games/mapgen/mods/valleys_mapgen/trees.lua:128: in function 'grow_jungle_tree'
    ...minetest/games/mapgen/mods/valleys_mapgen/mapgen.lua:322: in function '?'
    ...e/ivan/minetest-dev/bin/../builtin/game/register.lua:341: in function <...e/ivan/minetest-dev/bin/../builtin/game/register.lua:329>
Debug stacks:
DEBUG STACK FOR THREAD 7f57e119a700:
#0  virtual void\* EmergeThread::Thread()

(Leftover data: #1  virtual MapBlock\* ServerMap::emergeBlock(v3s16, bool): p=(-7,3,18), create_blank=0)
(Leftover data: #2  ServerMapSector\* ServerMap::createSector(v2s16): p2d=(-9,18))
DEBUG STACK FOR THREAD 7f57e199b700:
#0  virtual void\* ServerThread::Thread()
#1  void Server::Receive()

(Leftover data: #2  void Server::SendBlocks(float))
(Leftover data: #3  void Server::SendBlockNoLock(irr::u16, MapBlock_, irr::u8, irr::u16))
(Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
(Leftover data: #5  bool getCraftingResult(Inventory_, ItemStack&, bool, IGameDef*))
DEBUG STACK FOR THREAD 7f57e897e780:
#0  int main(int, char**)
#1  Dedicated server branch
#2  void dedicated_server_loop(Server&, bool&)
#3  void Server::step(float)

./mapgen.sh: line 1:  3119 Avortat                 ~/minetest-dev/bin/minetest --server --config /home/ivan/.minetest/games/mapgen/minetest.conf --worldname world --gameid mapgen

**Comment by gaelysam** [comment]
http://stackoverflow.com/questions/20171224/interval-is-empty-lua-math-random-isnt-working-for-large-numbers
I used a too large number for seed (2³²−1). It worked for me, I don't know why.
https://github.com/Gael-de-Sailly/valleys_mapgen/blob/master/trees.lua#L170
I will set it to 2²⁴.

**Comment by gaelysam** [comment]
ced4198

**Comment by ghost** [comment]
Thankyou @Gael-de-Sailly.

From the stackoverflow reply I understand that my minetest server isn't using LuaJIT... Now I should figure out why this happens, 'cause LuaJIT is installed on my sistem, and minetest documentation says that it use LuaJIT automagically if it's installed... :-/
